version: 2

models:
  - name: stg_raw_data_stone__transacoes_usuarios
    description: Dados de transação de usuários
    columns:
      - name: codigo_transacao
        description: Código único da transação
      - name: date_transacao
        description: Data e hora de criação da transação (UTC 0)
      - name: dispositivo_captura
        description: Dispositivo de captura (POS, Tapton ou Link de pagamento)
      - name: bandeira_cartao
        description: Bandeira do cartão
      - name: metodo_pagamento
        description: Método de pagamento
      - name: estado_transacao
        description: Estado da transação (valores aceitos. paid, refused, refunded e chargedback)
      - name: vl_transacao
        description: Valor da transação (R$)
      - name: codigo_usuario
        description: Código único do usuário
      - name: estado_usuario
        description: Estado único do usuário
      - name: cidade_usuario
        description: Cidade única do usuário